### ISSUE TITLE
Just a heads up for docker builds

### ISSUE THREAD

**Issue by jnc-nj** [AndreeaDogaru/Gen3DSR#4]
The provided scripts do not work as is -- natten requires GPU to build.

I circumvented this by building up to the natten bit, running the image, building natten, then committing the container as a checkpoint for the rest of the build.

Also, `aramnet_360cities_edina_rpfpp.pth` and `CIDAS/clipseg-rd64-refined` ought to be listed as requisites -- they can be found on huggingface.

**Comment by jnc-nj** [comment]
Also, sam_vit_h_4b8939.pth is always read from cache instead of the folder (so `/root/.cache/torch/hub/checkpoints/`), and openai' rn50x16 clip model should be listed as a  prerequisite, I'm not sure where that goes yet though.

**Comment by jnc-nj** [comment]
'https://github.com/danielgatis/rembg/releases/download/v0.0.0/isnet-general-use.onnx' to '/root/.u2net/isnet-general-use.onnx'

this should probably also be in the dockerfile

**Comment by AndreeaDogaru** [comment]
Thank you for your interest in our work and providing feedback on the docker build!
Let us know when you succeed running the model.
If you would like to make a pull request with the suggested fixes, I would be happy to check it out and merge the changes.

**Comment by jnc-nj** [comment]
Tbh the dockerfiles provided in the repo are sufficient, the extra downloads are unnecessary for users outside of China (where GitHub and huggingface are banned).

Perhaps a simple amendment to the readme for two dockerfiles instead of one would be better? The natten problem doesn't seem to have a workaround -- docker doesn't allow gpu access during the build process, and a lot of PyTorch builds come with the `-D_GLIBCXX_USE_CXX11_ABI=1` flag which forces gpu read. 

Considering most users won't build their own PyTorch.. it's probably easier to just do it the rough way. The guys in the natten official repo says this issue is fixed as of natten==0.17.1, but there are still reports of the same problem.

**Comment by jnc-nj** [comment]
> Thank you for your interest in our work and providing feedback on the docker build! Let us know when you succeed running the model. If you would like to make a pull request with the suggested fixes, I would be happy to check it out and merge the changes.

On a side note, the repo works as intended, but the models themselves still come out a bit wonky, I assume this is because of zero123. Have you thought about integrating zero123++ / zero123-xl / wonder3d? They seem to have better single object results in the wild.

Zero123-xl in particular might be the easiest to deal with -- it's from the original authors.

That or I'm missing something in the configs. This project is great though, best scene generation so far not using a gaussian splat technique I've seen.

**Comment by AndreeaDogaru** [comment]
I'm glad to hear you were successful in running the code. I'll keep the Docker recommendations in mind for future updates.

Regarding the reconstruction quality, we currently use DreamGaussian with Zero123-XL. DreamGaussian is not compatible with models such as [Zero123++](https://github.com/dreamgaussian/dreamgaussian/issues/56#issuecomment-1782551482), but we are experimenting with newer object reconstruction methods that we might integrate into our framework.
