### ISSUE TITLE
Code Snippet to Reproject Reconstructed Scene

### ISSUE THREAD

**Issue by yaojin17** [AndreeaDogaru/Gen3DSR#5]
Hi Author,

Thank you for your amazing work! I am currently trying out your code and have a question. I'm curious about how to reproject the reconstructed scene to match the same view as the input image, similar to the first two images in your README. Could you let me know which library you use for this projection? Additionally, could you provide a minimal code snippet to illustrate the process?

Thanks again!

**Comment by AndreeaDogaru** [comment]
Hi,
Thank you for your interest in our work!
The images you are referring to are rendered with Blender using the Cycles engine.
You can check out this script [load_blender.py](https://gist.github.com/AndreeaDogaru/8d4642db1b3692a71cdd36bae973e3e6) for loading the scene into Blender. It uses [BlenderProc](https://github.com/DLR-RM/BlenderProc) for setting the camera attributes, but you could probably achieve the same result using the bpy package.
`blenderproc debug load_blender.py `

**Comment by yaojin17** [comment]
Thank you so much for your detailed script!!!
