### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by Girin325** [AndreeaDogaru/Gen3DSR#6]
Dear author.
Your research is really interesting and great!
I would like to train with a custom dataset. 
Is there a separate code?

**Comment by AndreeaDogaru** [comment]
Hello,

Thank you for your interest in our research!
Please note that our method does not require any dataset-specific training, nor do we train the system end-to-end. Instead, we integrate pre-trained models into a pipeline that generalizes well and can perform 3D reconstruction of diverse scenes. You can read more about it in our [paper](https://arxiv.org/pdf/2404.03421). Therefore there is no training code.
